version: "3.8"

services:
  app:
    build:
      context: ./app
    image: golang:1.12.7-alpine3.10
    container_name: app
    volumes:
      - ./app/src:/go/src/app
    networks:
      - network

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - network
    depends_on:
      - "app"

  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - "app"
    networks:
      - network

networks:
  network:
    driver: bridge
