version: '3.8'

services:
  app:
    build:
      context: ./app
    image: golang:1.12.7-alpine3.10
    container_name: app
    volumes:
      - ./app/src:/go/src/app
    ports:
      - '8080'
  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    depends_on:
      - 'app'
